openapi: 3.1.0
info:
  version: 1.0.0
  title: Example.com
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
  description:
    $ref: ./info-description.md
servers:
  - url: 'https://secure.payu.com/api/v2_1'
    description: Production Server
  - url: 'https://secure.snd.payu.com/api/v2_1'
    description: Sandbox Test Server
paths:
  /orders:
    post:
      $ref: paths\orderCreateRequest.yaml
  /orders/{orderId}:
    get:
      $ref: paths\orderRetrieveRequest.yaml
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
